CREATE TABLE IF NOT EXISTS EVOLUTION (
AGE INTEGER,
NAME TEXT,
HABITATION TEXT,
SIZE TEXT
);

INSERT INTO EVOLUTION (AGE, NAME, HABITATION, SIZE) VALUES
(1004237, 'SHARK','AQUATIC', 'LARGE'),
(1564213, 'BEAR', 'LAND', 'MEDIUM'),
(250145, 'CHICKEN', 'LAND', 'SMALL'),
(768231, 'FROG', 'AMPHIBOUS', 'SMALL');

SELECT *
FROM EVOLUTION
WHERE SIZE NOT LIKE 'S%';